################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/STM32F4xx_HAL_Driver/Src \
Libs/lvgl/src/core \
Libs/lvgl/src/debugging/monkey \
Libs/lvgl/src/debugging/profiler \
Libs/lvgl/src/debugging/sysmon \
Libs/lvgl/src/debugging/test \
Libs/lvgl/src/debugging/vg_lite_tvg \
Libs/lvgl/src/display \
Libs/lvgl/src/draw/convert/helium \
Libs/lvgl/src/draw/convert \
Libs/lvgl/src/draw/convert/neon \
Libs/lvgl/src/draw/dma2d \
Libs/lvgl/src/draw/espressif/ppa \
Libs/lvgl/src/draw/eve \
Libs/lvgl/src/draw \
Libs/lvgl/src/draw/nanovg \
Libs/lvgl/src/draw/nema_gfx \
Libs/lvgl/src/draw/nxp/g2d \
Libs/lvgl/src/draw/nxp/pxp \
Libs/lvgl/src/draw/opengles \
Libs/lvgl/src/draw/renesas/dave2d \
Libs/lvgl/src/draw/sdl \
Libs/lvgl/src/draw/sifli/epic \
Libs/lvgl/src/draw/snapshot \
Libs/lvgl/src/draw/sw/blend/arm2d \
Libs/lvgl/src/draw/sw/blend/helium \
Libs/lvgl/src/draw/sw/blend \
Libs/lvgl/src/draw/sw/blend/neon \
Libs/lvgl/src/draw/sw/blend/riscv_v \
Libs/lvgl/src/draw/sw/blend/sve2 \
Libs/lvgl/src/draw/sw \
Libs/lvgl/src/draw/vg_lite \
Libs/lvgl/src/drivers/display/drm \
Libs/lvgl/src/drivers/display/fb \
Libs/lvgl/src/drivers/display/ft81x \
Libs/lvgl/src/drivers/display/mipi \
Libs/lvgl/src/drivers/display/nxp_elcdif \
Libs/lvgl/src/drivers/display/renesas_glcdc \
Libs/lvgl/src/drivers/display/st_ltdc \
Libs/lvgl/src/drivers/draw/eve \
Libs/lvgl/src/drivers/evdev \
Libs/lvgl/src/drivers/libinput \
Libs/lvgl/src/drivers/nuttx \
Libs/lvgl/src/drivers/opengles/assets \
Libs/lvgl/src/drivers/opengles/glad/src \
Libs/lvgl/src/drivers/opengles \
Libs/lvgl/src/drivers/opengles/opengl_shader \
Libs/lvgl/src/drivers/qnx \
Libs/lvgl/src/drivers/sdl \
Libs/lvgl/src/drivers/uefi \
Libs/lvgl/src/drivers/wayland \
Libs/lvgl/src/drivers/windows \
Libs/lvgl/src/drivers/x11 \
Libs/lvgl/src/font/binfont_loader \
Libs/lvgl/src/font/fmt_txt \
Libs/lvgl/src/font/font_manager \
Libs/lvgl/src/font/freetype \
Libs/lvgl/src/font/imgfont \
Libs/lvgl/src/font \
Libs/lvgl/src/font/tiny_ttf \
Libs/lvgl/src/fs \
Libs/lvgl/src/image \
Libs/lvgl/src/image/svg \
Libs/lvgl/src/indev \
Libs/lvgl/src/layouts/flex \
Libs/lvgl/src/layouts/grid \
Libs/lvgl/src/layouts \
Libs/lvgl/src/libs/FT800-FT813 \
Libs/lvgl/src/libs/barcode \
Libs/lvgl/src/libs/frogfs/src \
Libs/lvgl/src/libs/gif \
Libs/lvgl/src/libs/gltf/gltf_data \
Libs/lvgl/src/libs/gltf/gltf_environment \
Libs/lvgl/src/libs/gltf/gltf_view/assets \
Libs/lvgl/src/libs/gltf/math \
Libs/lvgl/src/libs/lodepng \
Libs/lvgl/src/libs/lz4 \
Libs/lvgl/src/libs/nanovg \
Libs/lvgl/src/libs/qrcode \
Libs/lvgl/src/libs/rle \
Libs/lvgl/src/libs/rlottie \
Libs/lvgl/src/libs/tjpgd \
Libs/lvgl/src/libs/vg_lite_driver/VGLite \
Libs/lvgl/src/libs/vg_lite_driver/VGLiteKernel \
Libs/lvgl/src/libs/vg_lite_driver/lv_vg_lite_hal \
Libs/lvgl/src/logging \
Libs/lvgl/src \
Libs/lvgl/src/misc/cache/class \
Libs/lvgl/src/misc/cache/instance \
Libs/lvgl/src/misc/cache \
Libs/lvgl/src/misc \
Libs/lvgl/src/osal \
Libs/lvgl/src/others/file_explorer \
Libs/lvgl/src/others/fragment \
Libs/lvgl/src/others/translation \
Libs/lvgl/src/stdlib/builtin \
Libs/lvgl/src/stdlib/clib \
Libs/lvgl/src/stdlib \
Libs/lvgl/src/stdlib/micropython \
Libs/lvgl/src/stdlib/rtthread \
Libs/lvgl/src/stdlib/uefi \
Libs/lvgl/src/themes/default \
Libs/lvgl/src/themes \
Libs/lvgl/src/themes/mono \
Libs/lvgl/src/themes/simple \
Libs/lvgl/src/tick \
Libs/lvgl/src/widgets/3dtexture \
Libs/lvgl/src/widgets/animimage \
Libs/lvgl/src/widgets/arc \
Libs/lvgl/src/widgets/arclabel \
Libs/lvgl/src/widgets/bar \
Libs/lvgl/src/widgets/barcode \
Libs/lvgl/src/widgets/button \
Libs/lvgl/src/widgets/buttonmatrix \
Libs/lvgl/src/widgets/calendar \
Libs/lvgl/src/widgets/canvas \
Libs/lvgl/src/widgets/chart \
Libs/lvgl/src/widgets/checkbox \
Libs/lvgl/src/widgets/dropdown \
Libs/lvgl/src/widgets/ffmpeg \
Libs/lvgl/src/widgets/gif \
Libs/lvgl/src/widgets/gstreamer \
Libs/lvgl/src/widgets/image \
Libs/lvgl/src/widgets/imagebutton \
Libs/lvgl/src/widgets/ime \
Libs/lvgl/src/widgets/keyboard \
Libs/lvgl/src/widgets/label \
Libs/lvgl/src/widgets/led \
Libs/lvgl/src/widgets/line \
Libs/lvgl/src/widgets/list \
Libs/lvgl/src/widgets/lottie \
Libs/lvgl/src/widgets/menu \
Libs/lvgl/src/widgets/msgbox \
Libs/lvgl/src/widgets/objx_templ \
Libs/lvgl/src/widgets/property \
Libs/lvgl/src/widgets/qrcode \
Libs/lvgl/src/widgets/roller \
Libs/lvgl/src/widgets/scale \
Libs/lvgl/src/widgets/slider \
Libs/lvgl/src/widgets/span \
Libs/lvgl/src/widgets/spinbox \
Libs/lvgl/src/widgets/spinner \
Libs/lvgl/src/widgets/switch \
Libs/lvgl/src/widgets/table \
Libs/lvgl/src/widgets/tabview \
Libs/lvgl/src/widgets/textarea \
Libs/lvgl/src/widgets/tileview \
Libs/lvgl/src/widgets/win \

