################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/STM32F4xx_HAL_Driver/Src \
Middlewares/lvgl/src/core \
Middlewares/lvgl/src/debugging/monkey \
Middlewares/lvgl/src/debugging/profiler \
Middlewares/lvgl/src/debugging/sysmon \
Middlewares/lvgl/src/debugging/test \
Middlewares/lvgl/src/debugging/vg_lite_tvg \
Middlewares/lvgl/src/display \
Middlewares/lvgl/src/draw/convert/helium \
Middlewares/lvgl/src/draw/convert \
Middlewares/lvgl/src/draw/convert/neon \
Middlewares/lvgl/src/draw/dma2d \
Middlewares/lvgl/src/draw/espressif/ppa \
Middlewares/lvgl/src/draw/eve \
Middlewares/lvgl/src/draw \
Middlewares/lvgl/src/draw/nanovg \
Middlewares/lvgl/src/draw/nema_gfx \
Middlewares/lvgl/src/draw/nxp/g2d \
Middlewares/lvgl/src/draw/nxp/pxp \
Middlewares/lvgl/src/draw/opengles \
Middlewares/lvgl/src/draw/renesas/dave2d \
Middlewares/lvgl/src/draw/sdl \
Middlewares/lvgl/src/draw/sifli/epic \
Middlewares/lvgl/src/draw/snapshot \
Middlewares/lvgl/src/draw/sw/blend/arm2d \
Middlewares/lvgl/src/draw/sw/blend/helium \
Middlewares/lvgl/src/draw/sw/blend \
Middlewares/lvgl/src/draw/sw/blend/neon \
Middlewares/lvgl/src/draw/sw/blend/riscv_v \
Middlewares/lvgl/src/draw/sw/blend/sve2 \
Middlewares/lvgl/src/draw/sw \
Middlewares/lvgl/src/draw/vg_lite \
Middlewares/lvgl/src/drivers/display/drm \
Middlewares/lvgl/src/drivers/display/fb \
Middlewares/lvgl/src/drivers/display/ft81x \
Middlewares/lvgl/src/drivers/display/mipi \
Middlewares/lvgl/src/drivers/display/nxp_elcdif \
Middlewares/lvgl/src/drivers/display/renesas_glcdc \
Middlewares/lvgl/src/drivers/display/st_ltdc \
Middlewares/lvgl/src/drivers/draw/eve \
Middlewares/lvgl/src/drivers/evdev \
Middlewares/lvgl/src/drivers/libinput \
Middlewares/lvgl/src/drivers/nuttx \
Middlewares/lvgl/src/drivers/opengles/assets \
Middlewares/lvgl/src/drivers/opengles/glad/src \
Middlewares/lvgl/src/drivers/opengles \
Middlewares/lvgl/src/drivers/opengles/opengl_shader \
Middlewares/lvgl/src/drivers/qnx \
Middlewares/lvgl/src/drivers/sdl \
Middlewares/lvgl/src/drivers/uefi \
Middlewares/lvgl/src/drivers/wayland \
Middlewares/lvgl/src/drivers/windows \
Middlewares/lvgl/src/drivers/x11 \
Middlewares/lvgl/src/font/binfont_loader \
Middlewares/lvgl/src/font/fmt_txt \
Middlewares/lvgl/src/font/font_manager \
Middlewares/lvgl/src/font/freetype \
Middlewares/lvgl/src/font/imgfont \
Middlewares/lvgl/src/font \
Middlewares/lvgl/src/font/tiny_ttf \
Middlewares/lvgl/src/fs \
Middlewares/lvgl/src/image \
Middlewares/lvgl/src/image/svg \
Middlewares/lvgl/src/indev \
Middlewares/lvgl/src/layouts/flex \
Middlewares/lvgl/src/layouts/grid \
Middlewares/lvgl/src/layouts \
Middlewares/lvgl/src/libs/FT800-FT813 \
Middlewares/lvgl/src/libs/barcode \
Middlewares/lvgl/src/libs/frogfs/src \
Middlewares/lvgl/src/libs/gif \
Middlewares/lvgl/src/libs/gltf/gltf_data \
Middlewares/lvgl/src/libs/gltf/gltf_environment \
Middlewares/lvgl/src/libs/gltf/gltf_view/assets \
Middlewares/lvgl/src/libs/gltf/math \
Middlewares/lvgl/src/libs/lodepng \
Middlewares/lvgl/src/libs/lz4 \
Middlewares/lvgl/src/libs/nanovg \
Middlewares/lvgl/src/libs/qrcode \
Middlewares/lvgl/src/libs/rle \
Middlewares/lvgl/src/libs/rlottie \
Middlewares/lvgl/src/libs/tjpgd \
Middlewares/lvgl/src/libs/vg_lite_driver/VGLite \
Middlewares/lvgl/src/libs/vg_lite_driver/VGLiteKernel \
Middlewares/lvgl/src/libs/vg_lite_driver/lv_vg_lite_hal \
Middlewares/lvgl/src/logging \
Middlewares/lvgl/src \
Middlewares/lvgl/src/misc/cache/class \
Middlewares/lvgl/src/misc/cache/instance \
Middlewares/lvgl/src/misc/cache \
Middlewares/lvgl/src/misc \
Middlewares/lvgl/src/osal \
Middlewares/lvgl/src/others/file_explorer \
Middlewares/lvgl/src/others/fragment \
Middlewares/lvgl/src/others/translation \
Middlewares/lvgl/src/stdlib/builtin \
Middlewares/lvgl/src/stdlib/clib \
Middlewares/lvgl/src/stdlib \
Middlewares/lvgl/src/stdlib/micropython \
Middlewares/lvgl/src/stdlib/rtthread \
Middlewares/lvgl/src/stdlib/uefi \
Middlewares/lvgl/src/themes/default \
Middlewares/lvgl/src/themes \
Middlewares/lvgl/src/themes/mono \
Middlewares/lvgl/src/themes/simple \
Middlewares/lvgl/src/tick \
Middlewares/lvgl/src/widgets/3dtexture \
Middlewares/lvgl/src/widgets/animimage \
Middlewares/lvgl/src/widgets/arc \
Middlewares/lvgl/src/widgets/arclabel \
Middlewares/lvgl/src/widgets/bar \
Middlewares/lvgl/src/widgets/barcode \
Middlewares/lvgl/src/widgets/button \
Middlewares/lvgl/src/widgets/buttonmatrix \
Middlewares/lvgl/src/widgets/calendar \
Middlewares/lvgl/src/widgets/canvas \
Middlewares/lvgl/src/widgets/chart \
Middlewares/lvgl/src/widgets/checkbox \
Middlewares/lvgl/src/widgets/dropdown \
Middlewares/lvgl/src/widgets/ffmpeg \
Middlewares/lvgl/src/widgets/gif \
Middlewares/lvgl/src/widgets/gstreamer \
Middlewares/lvgl/src/widgets/image \
Middlewares/lvgl/src/widgets/imagebutton \
Middlewares/lvgl/src/widgets/ime \
Middlewares/lvgl/src/widgets/keyboard \
Middlewares/lvgl/src/widgets/label \
Middlewares/lvgl/src/widgets/led \
Middlewares/lvgl/src/widgets/line \
Middlewares/lvgl/src/widgets/list \
Middlewares/lvgl/src/widgets/lottie \
Middlewares/lvgl/src/widgets/menu \
Middlewares/lvgl/src/widgets/msgbox \
Middlewares/lvgl/src/widgets/objx_templ \
Middlewares/lvgl/src/widgets/property \
Middlewares/lvgl/src/widgets/qrcode \
Middlewares/lvgl/src/widgets/roller \
Middlewares/lvgl/src/widgets/scale \
Middlewares/lvgl/src/widgets/slider \
Middlewares/lvgl/src/widgets/span \
Middlewares/lvgl/src/widgets/spinbox \
Middlewares/lvgl/src/widgets/spinner \
Middlewares/lvgl/src/widgets/switch \
Middlewares/lvgl/src/widgets/table \
Middlewares/lvgl/src/widgets/tabview \
Middlewares/lvgl/src/widgets/textarea \
Middlewares/lvgl/src/widgets/tileview \
Middlewares/lvgl/src/widgets/win \

