# Form implementation generated from reading ui file 'LineWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LineWindow(object):
    def setupUi(self, LineWindow):
        LineWindow.setObjectName("LineWindow")
        LineWindow.resize(584, 357)
        LineWindow.setStyleSheet("#centralwidget {\n"
"background-color: #d0e7f9;\n"
"border-image: url(:/fondo/bkg3.png) 0 0 0 0 stretch stretch; /* No cambiar esta linea de lugar*/\n"
"/*background-image:url(:/fondo/bkg3.png);  /* No cambiar esta linea de lugar*/\n"
"background-position: center center;\n"
"background-repeat: no-repeat;\n"
"\n"
"}\n"
"\n"
"/*QLabel*/\n"
"QLabel {\n"
"    color: #003865;\n"
"    font-size: 12pt;\n"
"    font-weight: 500;\n"
"    padding: 4px 8px;\n"
"    margin: 2px;\n"
"    border: none;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel:disabled {\n"
"    color: gray;\n"
"}\n"
"\n"
"QTabWidget {\n"
"    background-color: #d0e7f9;  /* Fondo del widget contenedor */\n"
"    border: none;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #003865;\n"
"    background: #eaf4fb;  /* Fondo del área activa del tab */\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: #6FB1FC;\n"
"    border: 1px solid #003865;\n"
"    padding: 8px 16px;\n"
"    margin-right: 2px;\n"
"    border-top-left-radius: 8px;\n"
"    border-top-right-radius: 8px;\n"
"    color: #003865;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #ffffff;\n"
"    border: 2px solid #003865;\n"
"    border-bottom: none;\n"
"    font-weight: bold;\n"
"    color: #003865;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: #A8D4FF;\n"
"}\n"
"\n"
"QWidget#tab,\n"
"QWidget#tab_2,\n"
"QWidget#tab_3,\n"
"QWidget#tab_4 {\n"
"    background-color: #eaf4fb;  /* Fondo para cada QWidget de pestaña */\n"
"}\n"
"\n"
"\n"
"\n"
"/*QCheckBox\n"
"QCheckBox {\n"
"color:white;\n"
"}*/\n"
"\n"
"/*QGroupBox\n"
"QGroupBox{\n"
"color:white;\n"
"text-align: center;\n"
"}*/\n"
"\n"
"QStatusBar {\n"
"    background-color: #b8d5ec;\n"
"    border-top: 1px solid #003865;\n"
"    color: #003865;\n"
"}\n"
"\n"
"/*QPushButton */\n"
"QPushButton {\n"
"    background-color: #6FB1FC;\n"
"    color: white;\n"
"    border: 1px solid #003865;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-size: 11pt;\n"
"    font-weight: 500;\n"
"    min-width: 200px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A8D4FF;\n"
"    border: 1px solid #003865;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4C97D2;\n"
"    border: 1px solid #002849;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #cccccc;\n"
"    color: #888888;\n"
"    border: 1px solid #aaaaaa;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    background-color: #f9fcff;\n"
"    color: #003865;\n"
"    border: 1px solid #003865;\n"
"    border-radius: 6px;\n"
"    padding: 8px;\n"
"    font-family: \"Segoe UI\", \"Arial\";\n"
"    font-size: 11pt;\n"
"    selection-background-color: #A8D4FF;\n"
"    selection-color: #000000;\n"
"}\n"
"\n"
"\n"
"/*QLineEdit*/\n"
"QLineEdit {\n"
"    background-color: transparent;    \n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: #003865;\n"
"    color: #003865;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color: gray;\n"
"}\n"
"\n"
"/*QDateEdit*/\n"
"QDateTimeEdit {\n"
"    color:black;\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1,y2:1, stop: 1 rgba(228, 255, 255, 255), stop: 0 rgba(150, 200, 100, 100));\n"
"    border-color: rgba(255,255,255,200);\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    padding: 1px 0px 1px 3px; /*This makes text colour work*/\n"
"}\n"
"\n"
"QDateEdit:disabled {\n"
"    color: gray;\n"
"}\n"
"\n"
"/*QComboBox*/\n"
"QComboBox {\n"
"    color: #003865;\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #6FB1FC;\n"
"    border-radius: 6px;\n"
"    padding: 4px 8px;\n"
"    font-size: 11pt;\n"
"    font-weight: 500;\n"
"    min-width: 200px;\n"
"    max-width: 300px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: #eaf4fb;\n"
"    border: 1px solid #003865;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border-left: 1px solid #6FB1FC;\n"
"    width: 20px;\n"
"    background-color: #6FB1FC;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    /* image: url(:/icons/down-arrow.svg); Opcional, o podés dejarlo por defecto */\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"/*QRadioButton */\n"
"QRadioButton {\n"
"  color:white;\n"
"}\n"
"\n"
"\n"
"/*TABLA*/\n"
"\n"
"QTableView {\n"
"    color: white;\n"
"    gridline-color: black;\n"
"    border-color: rgb(242, 128, 133);\n"
"     background-color: rgb(99, 176, 209);\n"
"    text-align:center;\n"
"    font-family: sans-serif;\n"
"}\n"
"QTableCornerButton::section {\n"
"    background-color: rgb(23, 63, 94);\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: rgb(23, 63, 94);\n"
"    color: white;\n"
"    text-align:center;\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"QScrollBar:vertical {\n"
"    background: rgb(188, 224, 235);\n"
"}\n"
" QScrollBar::handle:vertical {\n"
"    background: rgb(71, 153, 176);\n"
" }\n"
"QScrollBar:horizontal {\n"
"    background: rgb(188, 224, 235);\n"
"}\n"
" QScrollBar::handle:horizontal {\n"
"    background: rgb(71, 153, 176);\n"
" }\n"
"\n"
"QTableView::item:focus{\n"
"    border: 2px solid rgb(242, 128, 133);\n"
"    background: rgb(71, 153, 176);\n"
"    text-align:center;\n"
"}\n"
"QTableView::item:selected{\n"
"    border: 2px solid rgb(242, 128, 133);\n"
"    background: gray;\n"
"    text-align:center;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(LineWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=LineWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=LineWindow)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.LBL_multimetroEntrada = QtWidgets.QLCDNumber(parent=LineWindow)
        self.LBL_multimetroEntrada.setStyleSheet("\n"
"    QLCDNumber {\n"
"        background-color: #0A0F2C;       /* Azul muy oscuro */\n"
"        color: #86D1FF;                  /* Celeste eléctrico */\n"
"        border: 1px solid #1E3A8A;       /* Borde tenue */\n"
"        padding: 4px;\n"
"    }\n"
"")
        self.LBL_multimetroEntrada.setObjectName("LBL_multimetroEntrada")
        self.gridLayout.addWidget(self.LBL_multimetroEntrada, 1, 0, 1, 1)
        self.LBL_multimetroSalida = QtWidgets.QLCDNumber(parent=LineWindow)
        self.LBL_multimetroSalida.setStyleSheet("\n"
"    QLCDNumber {\n"
"        background-color: #0A0F2C;       /* Azul muy oscuro */\n"
"        color: #86D1FF;                  /* Celeste eléctrico */\n"
"        border: 1px solid #1E3A8A;       /* Borde tenue */\n"
"        padding: 4px;\n"
"    }\n"
"")
        self.LBL_multimetroSalida.setObjectName("LBL_multimetroSalida")
        self.gridLayout.addWidget(self.LBL_multimetroSalida, 1, 1, 1, 1)
        self.TestingSlide = QtWidgets.QSlider(parent=LineWindow)
        self.TestingSlide.setMaximum(999)
        self.TestingSlide.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.TestingSlide.setObjectName("TestingSlide")
        self.gridLayout.addWidget(self.TestingSlide, 2, 0, 1, 2)
        self.LBL_mensaje = QtWidgets.QLabel(parent=LineWindow)
        self.LBL_mensaje.setStyleSheet("QLabel {\n"
"    background-color: #dceeff;          /* celeste claro */\n"
"    color: #003366;                     /* azul profundo para buen contraste */\n"
"    border: 1px solid #80bfff;          /* borde azul suave */\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: Segoe UI, Arial, sans-serif;\n"
"}\n"
"")
        self.LBL_mensaje.setText("")
        self.LBL_mensaje.setObjectName("LBL_mensaje")
        self.gridLayout.addWidget(self.LBL_mensaje, 3, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.BTN_cancelar = QtWidgets.QPushButton(parent=LineWindow)
        self.BTN_cancelar.setObjectName("BTN_cancelar")
        self.horizontalLayout.addWidget(self.BTN_cancelar)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 2)

        self.retranslateUi(LineWindow)
        QtCore.QMetaObject.connectSlotsByName(LineWindow)

    def retranslateUi(self, LineWindow):
        _translate = QtCore.QCoreApplication.translate
        LineWindow.setWindowTitle(_translate("LineWindow", "Efecto de Linea"))
        self.label_2.setText(_translate("LineWindow", "Voltímetro de entrada"))
        self.label_3.setText(_translate("LineWindow", "Voltímetro de salida"))
        self.BTN_cancelar.setText(_translate("LineWindow", " Cancelar medición"))
